{% set name = "maptide" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/maptide-{{ version }}.tar.gz
  sha256: 1885fba5cc0a4d43dbaf24225580584afa22c5c569b41c44110850c98e7c3725

build:
  skip: True  # [py<39]
  entry_points:
    - maptide = maptide.cli:run
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('rust') }}
  host:
    - python
    - pip
    - maturin >=1.0,<2.0
  run:
    - python

test:
  imports:
    - maptide
  commands:
    - pip check
    - maptide --help
  requires:
    - pip

about:
  home: https://github.com/CLIMB-TRE/maptide
  summary: Base frequencies for BAM files.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tombch
